### ISSUE TITLE
Persistent selection

### ISSUE THREAD

**Issue by barryrowlingson** [stefanocudini/leaflet-geojson-selector#1]
I'm trying to use this plugin to implement polygon feature selection but I'm not sure if its possible just yet. Here's what I want to do...

Each feature and corresponding list element should either have default style, highlight style (when hovered over) or selected style (when clicked on). Selections could be exclusive (ie at most one feature selected at a time, clicking another feature de-selects any currently selected feature) or multiple (clicking toggles selection status).

I don't think this can be done with the current code base because the code only supports two styles, default and active, and I don't see how to extend this to selectable items. If I change the style of a selected feature on a click event it gets reset to default on mouseout events.

Is this possible now? Or is it worth implementing? I'm not much of a JS programmer but I'll do what I can....

**Comment by stefanocudini** [comment]
hi @barryrowlingson 
I think that your observations is very interesting!
The plugin is very recently only few days of life and it will be developed much better next times, if you want to help me you are welcome, has been trough for generic geographic selection.

I'm split this issue in other two: #3 #2 

I gave a look at your code github, congratulations for your software, I hope to tool works often to my work together with my colleague @simonefenix
