### ISSUE TITLE
Update list in function of view

### ISSUE THREAD

**Issue by SilentT-FR** [stefanocudini/leaflet-geojson-selector#10]
to continue https://github.com/stefanocudini/leaflet-list-markers/issues/3#issuecomment-148653257

Its possibly to use option to update the list (when move) for show only json features on view

**Comment by stefanocudini** [comment]
@SilentT-FR great idea!  I'll add it

**Comment by stefanocudini** [comment]
have you just a fork for this feature?

**Comment by SilentT-FR** [comment]
No ...

**Comment by stefanocudini** [comment]
@SilentT-FR can you suggest a good name for this option?
for example **showVisibleItems**, **listOnlyVisibleLayer**.. or?

**Comment by SilentT-FR** [comment]
Live list

**Comment by stefanocudini** [comment]
I'm just added new option: listOnlyVisibleLayers
