### ISSUE TITLE
custom style for each geojson feature/items

### ISSUE THREAD

**Issue by stefanocudini** [stefanocudini/leaflet-geojson-selector#3]
proposed by #1

**Comment by stefanocudini** [comment]
proposed by #1

**Comment by stefanocudini** [comment]
@barryrowlingson about this.. cloud be best solution is adding new option for specify property name inside each geojson feature to retrive the applicable style

**Comment by barryrowlingson** [comment]
I think a custom style for each feature isn't this plugin's job to control! The user should style features as they want in their code. The plugin should have its style for highlighting or selection, apply that when appropriate, and revert to the feature's previous style when finished highlighting/selecting.

**Comment by stefanocudini** [comment]
you are right!
